Animations explicit
ytskk/places pull request #39
Opened 2022-07-18 14:03 UTC by ytskk

2022-07-20 15:34 UTC, GeorgeOblomov commented on lib/data/db/app_db.dart
> +  }
Думаю выглядело бы более лаконично через `_favorites.add()`

2022-07-20 15:35 UTC, GeorgeOblomov commented on lib/data/db/app_db.dart
> +    _favorites = _favorites.where((element) => element.id != place.id).toList();
А здесь через `.removeWhere()`
И не нужно будет переприсваивать значение переменной.

2022-07-20 15:40 UTC, GeorgeOblomov commented on lib/ui/screens/onboarding/onboarding_screen.dart
> +          // ),
Вы оставляете комментарии потому-что хотите позже применить эти элементы?
Я думаю, можно смело избавляться от не нужного кода. А в случае надобности можно в истории изменений подсмотреть и вернуть обратно.

2022-07-20 15:50 UTC, GeorgeOblomov commented on lib/ui/components/image/load_network_image.dart
> +      frameBuilder: (context, child, frame, wasSynchronouslyLoaded) {
Принято в подобных коллбеках, параметры которые в теле использоваться не будут заменять на прочерки. Чтобы не создавать путаницы.
```dart
frameBuilder: (_, child, __, wasSynchronousLoaded) => ...
```

2022-07-20 15:51 UTC, GeorgeOblomov requested changes
С анимациями проблем не вижу, считаю задание выполненным, но давайте немного поправим для красоты.

2022-07-21 07:10 UTC, ytskk commented
https://user-images.githubusercontent.com/57366771/180151998-a2ce6e25-4f42-4762-9104-512ca6227a43.mp4

2022-07-22 09:47 UTC, merged